### ISSUE TITLE
Library use case and examples?

### ISSUE THREAD

**Issue by markerikson** [i-think-rapido/redux-multistore#1]
You've got _something_ going on here, but I'm having a hard time understanding what this is or how to use it just from skimming the library could.  Could you add some documentation and examples to better explain what this does?

**Comment by thinkrapido** [comment]
Hi, Mark, I'm currently working on a new release of this library containing examples, documentation and a full readme. Be patient. I will release it within the next days. (mayby today :) )

**Comment by thinkrapido** [comment]
Version 0.2.0 is out now.
I'm curious about your experience and appreciate any comments.

**Comment by thinkrapido** [comment]
Version 0.3.1 is out now.
